output "resource_group_name" {
  value = azurerm_resource_group.rg.name
}

output "location" {
  value = azurerm_resource_group.rg.location
}

output "artifact_signing_account_id" {
  value = azapi_resource.code_signing_account.id
}

output "artifact_signing_account_name" {
  value = azapi_resource.code_signing_account.name
}

output "artifact_signing_endpoint" {
  value       = local.artifact_signing_endpoint
  description = "Region-specific endpoint used in metadata.json for signing."
}

output "certificate_profile_id" {
  value       = length(azapi_resource.certificate_profile) > 0 ? azapi_resource.certificate_profile[0].id : null
  description = "Certificate profile resource ID (null until identity_validation_id is provided)."
}

output "certificate_profile_name" {
  value       = length(azapi_resource.certificate_profile) > 0 ? azapi_resource.certificate_profile[0].name : null
  description = "Certificate profile name (null until created)."
}

output "ado_app_client_id" {
  value       = var.ado_enabled && var.ado_create_app ? azuread_application.ado_app[0].client_id : null
  description = "Client ID for the Entra app registration to use in the Azure DevOps service connection."
}

output "ado_sp_object_id" {
  value       = var.ado_enabled ? local.ado_sp_object_id_effective : null
  description = "Object ID for the Azure DevOps service principal used by the service connection (useful for troubleshooting RBAC)."
}

output "ado_project_id" {
  value       = var.ado_enabled ? azuredevops_project.project[0].id : null
  description = "Azure DevOps project ID (null unless ado_enabled=true)."
}

output "ado_repo_remote_url" {
  value       = var.ado_enabled ? azuredevops_git_repository.repo[0].remote_url : null
  description = "Azure DevOps repo HTTPS clone URL (null unless ado_enabled=true)."
}

output "ado_pipeline_id" {
  value       = var.ado_enabled ? azuredevops_build_definition.pipeline[0].id : null
  description = "Azure DevOps pipeline (build definition) ID (null unless ado_enabled=true)."
}

output "ado_service_connection_id" {
  value       = var.ado_enabled ? azuredevops_serviceendpoint_azurerm.azurerm[0].id : null
  description = "AzureRM service connection ID (null unless ado_enabled=true)."
}

output "ado_wif_issuer" {
  value       = var.ado_enabled ? try(azuredevops_serviceendpoint_azurerm.azurerm[0].workload_identity_federation_issuer, null) : null
  description = "WIF issuer generated by Azure DevOps for the service connection (null unless WIF scheme is used)."
}

output "ado_wif_subject" {
  value       = var.ado_enabled ? try(azuredevops_serviceendpoint_azurerm.azurerm[0].workload_identity_federation_subject, null) : null
  description = "WIF subject generated by Azure DevOps for the service connection (null unless WIF scheme is used)."
}

output "keyvault_id" {
  value       = var.keyvault_enabled ? azurerm_key_vault.kv[0].id : null
  description = "Key Vault resource ID (null unless keyvault_enabled=true)."
}

output "keyvault_name" {
  value       = var.keyvault_enabled ? local.keyvault_name_effective : null
  description = "Key Vault name (null unless keyvault_enabled=true)."
}
